{
    # Informacion basica del modulo
    'name': 'Meeting Room Booking',
    'version': '1.0',
    'summary': 'Gestion y reserva de salas de reuniones',
    'author': 'Generated by Codex',
    'category': 'Tools',
    'license': 'LGPL-3',
    'depends': ['base'],
    'data': [
        'security/ir.model.access.csv',
        'views/room_views.xml',
        'views/booking_views.xml',
        'views/actions.xml',
        'views/menus.xml',
    ],
    'application': True,
    'installable': True,
}
